"""app_settings (LLM provider config)

Revision ID: fb49db08f9a6
Revises: ec7554e27ae8
Create Date: 2026-05-29 17:00:47.774123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb49db08f9a6'
down_revision: Union[str, None] = 'ec7554e27ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('llm_provider', sa.String(length=20), nullable=False),
    sa.Column('ollama_base_url', sa.String(length=255), nullable=False),
    sa.Column('ollama_model', sa.String(length=100), nullable=False),
    sa.Column('openrouter_api_key', sa.String(length=255), nullable=False),
    sa.Column('openrouter_model', sa.String(length=100), nullable=False),
    sa.Column('openrouter_base_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
